name: fawori_admin
description: لوحة تحكم شركة فاوري
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  excel: ^4.0.6
  barcode_widget: ^2.0.3

flutter:
  uses-material-design: true
